/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ingenieria1202410;

import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author josearielpereyra
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private PanelDeDibujo panelDeDibujo;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setSize(800, 600);
        setIconImage(new ImageIcon(getClass().getResource("/IMG/icono.png")).getImage());

        panelDeDibujo = new PanelDeDibujo();

        JPanel containerPanel = new JPanel();
        containerPanel.setLayout(new BorderLayout());

        containerPanel.add(panelDeDibujo, BorderLayout.CENTER);
        getContentPane().add(containerPanel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDeBotones = new javax.swing.ButtonGroup();
        panelSpuerior = new java.awt.Panel();
        panelIzquierdo = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        blapiz = new javax.swing.JToggleButton();
        brectangulo = new javax.swing.JToggleButton();
        blinea = new javax.swing.JToggleButton();
        panelInferior = new java.awt.Panel();
        panelDerecho = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("  DIBUJADOR  3000");
        setIconImage(getIconImage());
        setIconImages(null);
        getContentPane().add(panelSpuerior, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(60, 100));

        grupoDeBotones.add(blapiz);
        blapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/lapiz.png"))); // NOI18N
        blapiz.setToolTipText("");
        blapiz.setBorder(null);
        blapiz.setBorderPainted(false);
        blapiz.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        blapiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blapizActionPerformed(evt);
            }
        });

        grupoDeBotones.add(brectangulo);
        brectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/rectangulo.png"))); // NOI18N
        brectangulo.setBorder(null);
        brectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brectanguloActionPerformed(evt);
            }
        });

        grupoDeBotones.add(blinea);
        blinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/linea.png"))); // NOI18N
        blinea.setBorder(null);
        blinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blineaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brectangulo)
                    .addComponent(blapiz)
                    .addComponent(blinea))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(blapiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blinea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(brectangulo)
                .addGap(40, 40, 40))
        );

        panelIzquierdo.add(jPanel1);

        getContentPane().add(panelIzquierdo, java.awt.BorderLayout.LINE_START);
        getContentPane().add(panelInferior, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(panelDerecho, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blapizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blapizActionPerformed
        // TODO add your handling code here:
        if (blapiz.isSelected()) {
            panelDeDibujo.observaActividad(true);
            
        } else {
            panelDeDibujo.observaActividad(false);
        }
        panelDeDibujo.recibeDatos("Lapiz");
        Image imagen = new ImageIcon(getClass().getResource("/IMG/lapiz.png")).getImage();
        Cursor cursor = Toolkit.getDefaultToolkit().createCustomCursor(imagen, new Point(0,32),"Lapiz");
        
        setCursor(cursor);
       
    }//GEN-LAST:event_blapizActionPerformed

    private void blineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blineaActionPerformed
        // TODO add your handling code here:
        if (blinea.isSelected()) {
            panelDeDibujo.observaActividad(true);
        } else {
            panelDeDibujo.observaActividad(false);
        }
        panelDeDibujo.recibeDatos("Linea");

    }//GEN-LAST:event_blineaActionPerformed

    private void brectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brectanguloActionPerformed
        // TODO add your handling code here:
        if (brectangulo.isSelected()) {
            panelDeDibujo.observaActividad(true);
        } else {
            panelDeDibujo.observaActividad(false);
        }
        panelDeDibujo.recibeDatos("Rectangulo");
    }//GEN-LAST:event_brectanguloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton blapiz;
    private javax.swing.JToggleButton blinea;
    private javax.swing.JToggleButton brectangulo;
    private javax.swing.ButtonGroup grupoDeBotones;
    private javax.swing.JPanel jPanel1;
    private java.awt.Panel panelDerecho;
    private java.awt.Panel panelInferior;
    private java.awt.Panel panelIzquierdo;
    private java.awt.Panel panelSpuerior;
    // End of variables declaration//GEN-END:variables
}
